### ISSUE TITLE
Nothing listening on port 80? 

### ISSUE THREAD

**Issue by dalbrightgit** [grafolean/grafolean#14]
Hello, apologies for the beginner nature of my question.   I followed all of the instructions on the site til the point where it says to load the web page on port 80.   There is no response.  

If I run a docker container ls command, I do not see any containers listening on port 80: 
<img width="1255" alt="Screen Shot 2021-02-23 at 8 12 43 PM" src="https://user-images.githubusercontent.com/79554063/108935559-89020800-7613-11eb-89eb-3762fd607a1a.png">

I am trying to set up a Raspberry Pi based monitor.  Many thanks in advance.

**Comment by grafolean** [comment]
Hi, no problem, it's actually not your fault - I didn't add instructions for RaspberryPi yet, sorry about that.

The reason nothing is listening is because there is something wrong with the services (most of them are starting or restarting). `docker-compose logs -f` would show you the reason, but I am guessing it will be wrong architecture.

Can you try using the `docker-compose.yml` as noted [here](https://github.com/grafolean/grafolean/issues/12#issuecomment-764943276)?

Let me know if you encounter any further problems.

**Comment by dalbrightgit** [comment]
thank you this was very helpful!  Amazing support.   I think got the images running, and I can now access the server on port 80.   My next issue is that the server just shows the following screen, with no action upon pressing "Upgrade DB".   
<img width="543" alt="Screen Shot 2021-02-24 at 7 35 31 PM" src="https://user-images.githubusercontent.com/79554063/109090442-933a0a00-76d8-11eb-8302-4f6c7003a5a8.png">

I have tried removing / rebuilding all of the docker images (sorry if the terminology is wrong), but every time I come back to the same error?  I thought about deleting the DB to let Grafolean rebuild it, but I can't locate it.   Semi-separately, is there a way I can put the database onto a mounted USB Drive so that it is not using the SD Card? 

Many thanks in advance!

**Comment by grafolean** [comment]
Ok, so clicking "Upgrade DB" should trigger a call to the backend, which should... well, upgrade the database. :) Can you maybe check (and share) the logs?

```
$ docker-compose logs -f grafolean
```

You can also check the logs for the database, in case there is something wrong with that:
```
$ docker-compose logs -f db
```

> Semi-separately, is there a way I can put the database onto a mounted USB Drive so that it is not using the SD Card?

Yes, absolutely. There is a `DB_DIR` setting in `.env` where you can use a completely different directory, so you can simply mount USB drive somewhere and then point Grafolean database to a subdirectory there.

**Comment by dalbrightgit** [comment]
Seems easy enough!, and I'm sorry I see you specifically said how to locate the db in the instructions. I blow away all of the docker images, deleted the db directory, edited the .env for the new db directory, did a docker-compose up and it all seems to be working.   the database is created, and now I'm working through some nuances of creating a user.   Thanks so much!

**Comment by grafolean** [comment]
Glad to hear you managed to fix it. I assume that the old database folder was broken in some way, or sth. similar... Since this seems solved I will close this issue, but feel free to comment (or open a new one) if you stumble across something else or if you are missing some features.

Have fun! :)
