### ISSUE TITLE
Egress Netflow Data

### ISSUE THREAD

**Issue by cherbold24** [grafolean/grafolean#16]
I am not seeing any egress data within the Netflow dashboard. I assume it is partially related to the issue you resolved with the netflow issues I was seeing in the previous issue. 

<img width="1116" alt="Screen Shot 2021-02-25 at 8 19 48 PM" src="https://user-images.githubusercontent.com/79016287/109245965-04e08980-77a7-11eb-9046-8b1ec0b443b6.png">

**Comment by grafolean** [comment]
No, that shouldn't be it - the Options Templates help with things like interface names, but they don't carry the traffic information (afaik). 

Can you maybe check that your exporter is setup to be sending the egress traffic too?

**Comment by cherbold24** [comment]
Below is an excerpt of the Netflow Packet trace seems to show both egress and ingress

excerpt of fortinet config:
--
edit "wan1"
set netflow-sampler both
--

FlowSet 10 [id=262] (1 flows)
        FlowSet Id: (Data) (262)
        FlowSet Length: 84
        [Template Frame: 5]
        Flow 1
            Octets: 134
            Post Octets: 134
            Packets: 1
            Post Packets: 1
            [Duration: 0.060000000 seconds (switched)]
            SrcPort: 53
            DstPort: 54521
            InputInt: 1
            OutputInt: 11
            Protocol: UDP (17)
            Post Ip Diff Serv Code Point: 64
            Classification Engine ID: PANA-L7-PEN (20)
            Selector ID: 0000304400000000
            Unknown Field Type: Type 66: Value (hex bytes): 00 00 00 00
            Unknown Field Type: Type 65: Value (hex bytes): 0c 44
            Forwarding Status
            Flow End Reason: Unknown (0)
            SrcAddr: 8.8.8.8
            DstAddr: x.x.x.x
            Post NAT Source IPv4 Address: 0.0.0.0
            Post NAT Destination IPv4 Address: x.x.x.x
            Post NAPT Source Transport Port: 0
            Post NAPT Destination Transport Port: 54521
        Padding: 00

     
    FlowSet 1 [id=262] (1 flows)
        FlowSet Id: (Data) (262)
        FlowSet Length: 84
        [Template Frame: 5]
        Flow 1
            Octets: 74
            Post Octets: 74
            Packets: 1
            Post Packets: 1
            [Duration: 0.040000000 seconds (switched)]
            SrcPort: 55673
            DstPort: 53
            InputInt: 11
            OutputInt: 1
            Protocol: UDP (17)
            Post Ip Diff Serv Code Point: 64
            Classification Engine ID: PANA-L7-PEN (20)
            Selector ID: 0000304400000000
            Unknown Field Type: Type 66: Value (hex bytes): 00 00 00 00
            Unknown Field Type: Type 65: Value (hex bytes): 0c 44
            Forwarding Status
            Flow End Reason: Unknown (0)
            SrcAddr: x.x.x.x.x
            DstAddr: 8.8.8.8
            Post NAT Source IPv4 Address: x.x.x.x
            Post NAT Destination IPv4 Address: 0.0.0.0
            Post NAPT Source Transport Port: 55673
            Post NAPT Destination Transport Port: 0
        Padding: 00

**Comment by grafolean** [comment]
I'm sorry, I don't see this from the exceprt, can you maybe highlight what you mean? What I would expect is seeing field `Direction` with value `1`.

Maybe you already know this, but just to make sure we are on the same page here... "egress" in NetFlow means outgoing from the *interface* (and not network) and should in most cases be exactly the same as ingress (the exception being compression on the device before transmitting data further). At least this is my understanding, but I'd be happy to learn more if I'm missing something?

**Comment by cherbold24** [comment]
So it looks like based on the template that is sent that the Fortigate doesn't send the direction field with both defined in the setup. I was looking at the InputInt: and OutputInt: fields. knowing the interfaces I had set.

**Comment by grafolean** [comment]
Just to clarify for future searchers: if `Direction` is not specified, it is `ingress` (`0`), so the traffic is already included in `ingress` part of the dashboard. I will keep in mind that this might be a bit misleading and will see if I can come up with a clearer UI in the future.

Since this seems solved I will close the issue, but feel free to reopen it (not sure if GitHub allows that) or open a new one if you have further questions.
