### ISSUE TITLE
Dashboard is completely white!

### ISSUE THREAD

**Issue by keithy999** [grafolean/grafolean#23]
Hi There,

Thanks for this cool project, sadly i just can't get it to work :(

I have installed it locally on my Linux PC to collect netflow data from a MikroTik router which is the router for this LAN.

The netflow exporter showed up automatically. I have enabled the netflow sensor and the logs show netflow data coming in to Grafolean.

When I add a dashboard using netflow template I get a completely white browser window. clicking refresh VERY briefly shows Grafolean web page and then reverts to completely white. I have tried various different browsers and disabled ad blockers etc etc.

Please help!

Thanks

**Comment by grafolean** [comment]
Hi @keithy999, can you maybe check Dev Tools Console (it usually shows up if you press F12, but it depends a bit on OS and browser) for any error messages? It sounds like some exception is being thrown and not handled right, sorry about that... If you can copy the error message here I'll try to fix it asap.

**Comment by keithy999** [comment]
[192.168.88.142-1624133314500.log](https://github.com/grafolean/grafolean/files/6681292/192.168.88.142-1624133314500.log)
[192.168.88.142-1624133359341.log](https://github.com/grafolean/grafolean/files/6681293/192.168.88.142-1624133359341.log)
Hi

I hope this is what you're after? If not can you send explicit instructions. I can use any browser. this was generated in Vivaldi (chromium based) running on Linux (Endeavouros - i.e. arch based)

Thanks

**Comment by grafolean** [comment]
Yes, this is exactly what I needed to reproduce and fix the bug, thank you!

Bug should be fixed in version v0.4.30, can you maybe upgrade and let me know if this fixes the issue for you?

**Comment by keithy999** [comment]
All working now. Thanks for the quick fix :)

**Comment by grafolean** [comment]
Glad to hear that, closing the issue. :+1:
