### ISSUE TITLE
No netflow data found for job - Mikrotik IPv6 Enabled

### ISSUE THREAD

**Issue by alien8tive** [grafolean/grafolean#28]
Hi,

Thanks for this useful tool.

This is a follow up on issue [netflow-writer errors](https://github.com/grafolean/grafolean/issues/5)

If the IPv6 package is enabled on Mikrotik, the data gets sent to the netflowbot, but nothing is displayed on the dashboard and the log display that there is no netflow data found. The error on the writer looks something like this:

`Sequence number (17) does not follow (15), some records might have been skipped`

Disabling IPv6 on the Mikrotik, rebooting and sending the data again, everything works fine. I do, however, run IPv6 natively and it would be nice to be able to use your tool.

I am using the latest versions in the docker-compose file.

`# grep "image: grafolean/" docker-compose.yml `

    image: grafolean/grafolean
    image: grafolean/mosquitto
    image: grafolean/grafolean-ping-bot
    image: grafolean/grafolean-snmp-bot
    image: grafolean/grafolean-netflow-bot
    image: grafolean/grafolean-netflow-bot
    image: grafolean/grafolean-netflow-bot`

**Comment by grafolean** [comment]
Hi,

The IPv6 should work (though I don't have a network at hand where I could test it). Can I ask a few clarification questions?

- Is there any other error or warning in the logs? 
- Which OS?
- Which version of grafolean-netflow-bot are you using? (`docker images | grep netflow` should show the ID of docker image, if you don't know it)

**Comment by alien8tive** [comment]
Hi. Thanks for the reply. I get this error in the Netflow writer:

`2022-04-24 20:33:59.828 | ERR | [192.168.254.1] Sequence number (0) does not follow (12), some records might have been skipped`
`2022-04-24 20:33:59.829 | ERR | Error writing line, skipping...`

The bot just inserts message that there is no netflow data and I do see that in the netflow_flows2 table in the postgres database. Running it on a Mikrotik with the IPv6 package disabled (on RouterOS version 6.49.5), the flows are written in this table. Eg.

`grafolean=# select * from netflow_flows2;`
`             ts             |  client_ip   | in_bytes | protocol | direction | l4_dst_port | l4_src_port | input_snmp | output_snmp |  ipvx_dst_addr  |  ipvx_src_addr`
`----------------------------+--------------+----------+----------+-----------+-------------+-------------+------------+-------------+-----------------+-----------------`
 `2022-04-25 05:31:28.790916 | 192.168.14.5 |       76 |       17 |         0 |         123 |         123 |          0 |           3 | 196.44.32.36    | 192.168.14.5`
 `2022-04-25 05:31:28.790916 | 192.168.14.5 |       76 |       17 |         0 |         123 |         123 |          3 |           0 | 192.168.14.5    | 196.44.32.36`


Running on Ubuntu 20.04 and the versions are

`# docker images | grep netflow   `                                                                                  
`grafolean/grafolean-netflow-bot              v0.3.3-rc.1         32e3d6375ded   14 months ago   115MB`
`grafolean/grafolean-netflow-bot              latest              784c36fb3b14   14 months ago   115MB`
`grafolean/grafolean-netflow-bot              v0.3.0              6b34cc76f02b   17 months ago   114MB`

Note: I tried other versions to test, but reverted back to the latest.

**Comment by grafolean** [comment]
The error indicates that there was something wrong with decoding the packets.

Do you think it would be possible for you to record some traffic (what is being sent to Grafolean Netflow bot) and send the PCAP to me via e-mail (anze at grafolean.com)? If you need help recording, let me know.

If not, I can try to setup something here and see if I can reproduce the problem, but it would probably take more time and I might not be able to replicate your exact issue.

**Comment by alien8tive** [comment]
Thanks. I’m out of town currently and will be able to capture the packets when Im back, next week.

**Comment by grafolean** [comment]
Thank you for sending the PCAP file, I was able to replay it and track down the issue. The problem was in a wrong assumption about how many bytes fields input_snmp and output_snmp take (I was assuming it was 2 bytes, the same as with V5, but it can be more).

I have now fixed the issue and prepared a new netflow bot image (`v0.3.4`).

You should be able to upgrade it [as usual](https://github.com/grafolean/grafolean#upgrading). Let me know if this works for you now, and thank you again for reporting this!

**Comment by alien8tive** [comment]
Great stuff! It works!

I've updated and the Mikrotik router with IPv6 enabled is now successfully loading the graphs.

Thank you for your assistance. I am closing this ticket.
