### ISSUE TITLE
support sflow v5?

### ISSUE THREAD

**Issue by mraxu** [grafolean/grafolean#29]

**Comment by grafolean** [comment]
Hi @mraxu,

If you are asking if sflow is supported, then no, Grafolean currently doesn't have an agent (bot) that would support sflow. There is no technical reason for it, it just wasn't implemented (yet?). I see there are some Python and Go libraries that can decode sflow data so it shouldn't be too hard to do it.

That said, I don't currently have an environment to test during development, nor do I have a particular need for it. If someone is willing to develop something I would be happy to review a PR though.

Closing this, but feel free to reopen (or open a new issue) if you feel you could contribute.
