### ISSUE TITLE
How to configure Netflow for this software?

### ISSUE THREAD

**Issue by tkalfaoglu** [grafolean/grafolean#34]
Do we still use port 2055 when configuring a CISCO router?
Do we specify a version like 5 or 9?
There is no mention in the documentation about how to configure the router side..
Thanks

**Comment by grafolean** [comment]
Yes - tutorials on how to configure Netflow are out of scope of this project.

About the port, you are free to specify any port you wish, though it might make your life easier to stick to he standard ones.

Closing this issue as it is out of scope, but feel free to leave a note pointing others to any good resources you might find. Good luck!
