### ISSUE TITLE
netflow does not work

### ISSUE THREAD

**Issue by tkalfaoglu** [grafolean/grafolean#35]
Couldn't get netflow to work. no data received.
tried to install the netflow bot by itself but this returns blank
curl https://github.com/grafolean/grafolean-netflow-bot/raw/master/docker-compose.yml

**Comment by grafolean** [comment]
Can you describe in more detail?

Three things will help diagnose the problem and hopefully solve it:
1) what did you do? (detailed steps, screenshots help a lot here)
2) what were you expecting would happen?
3) what happened? (logs are a great addition, but even an error message or description of state would help)

**Comment by grafolean** [comment]
Closing this issue because it doesn't have enough information, but feel free to reopen if you still need help with this.
