### ISSUE TITLE
Ubuntu 22.04 -  The database must be upgraded before we can proceed.

### ISSUE THREAD

**Issue by SilverNodashi** [grafolean/grafolean#36]
I followed the installation instructions on a newly installed Ubuntu Ubuntu 22.04.3 LTS VM, with Docker version 24.0.6, build ed223bc installed. 

The only change I made to the .env file was add the IP address
`user@grafolen:~$ more .env 
EXTERNAL_HOSTNAME=192.168.100.156
DB_DIR=/grafolean-db/
DB_NAME=grafolean
DB_USER=admin
DB_PASS=admin
HTTP_PORT=80

# Options: full, none or basic (default).
TELEMETRY=basic
rudi@grafolen:~$ 
`

Upon opening http://192.168.100.156 I get a message, "The database must be upgraded before we can proceed." Clicking on the Upgrade button doesn't do anything.

**Comment by grafolean** [comment]
Hi!

Unfortunately I can't check right now, however the symptoms you  
describe are very similar to this issue:  
https://github.com/grafolean/grafolean/issues/33

Can you maybe follow the advice there and see if that solves the issue?

**Comment by SilverNodashi** [comment]
Which OS is recommended for grafolean?

I have added the IP address to _GRAFOLEAN_CORS_DOMAINS,_ as per [#33 ](https://github.com/grafolean/grafolean/issues/33)but still get the same error. 

When running _docker logs grafolean_ I get this: 

 


![image](https://github.com/grafolean/grafolean/assets/17824870/ee5da550-d95d-4d1e-9da5-686aa2ecfe43)

**Comment by grafolean** [comment]
Ubuntu is fine. Actually, any Linux should be fine, as long as Docker  
is installed.

Thanks for posting the log, it looks like one of the database  
migrations (26) is failing.

Are you migrating an existing database? That is, are you upgrading  
from a previous version and you already have some data?

**Comment by SilverNodashi** [comment]
No. 

This is a new installation.

**Comment by grafolean** [comment]
First, sorry for late response, I didn't have access to my machine. I have now tried installing Grafolean again as per [instructions](https://github.com/grafolean/grafolean#installation) to make sure there is no regression, but it went smoothly in my case.

The log that you posted shows that it gets stuck in migration 26, trying to drop index `measurements_path_ts`, which was created in migration 1. The only possible explanation that I can think of is that it fails already sooner, in a different step of migration 26 - and then can't drop the index *again*. Would it be possible for you to start installation again, and to post the logs of the first migration until the first error? That is, the logs should start with `"Migrating DB schema from 0 to 1"` and end with error...

Apart from that, OS version should have no effect on Grafolean installation or operation. Is there something specific in how Grafolean is installed? Did you maybe change docker-compose.yml in any way?

**Comment by grafolean** [comment]
Closing this as stale, feel free to reopen if it still happens.
