### ISSUE TITLE
Unable to login on fresh deployment

### ISSUE THREAD

**Issue by smccloud** [grafolean/grafolean#42]
I just deployed Grafolean using the directions.  The error I am getting in the browser console is unable to connect to MQTT.  Console logs below, grafolean.unimax.local does point to the correct IP in our DNS.

> paho-mqtt-min.js:37 WebSocket connection to 'ws://grafolean.unimax.local/mqtt' failed: 
> d._doConnect @ paho-mqtt-min.js:37
> d.connect @ paho-mqtt-min.js:31
> G.connect @ paho-mqtt-min.js:69
> (anonymous) @ MQTTFetcherSingleton.js:128
> ensureMqttConnected @ MQTTFetcherSingleton.js:115
> t.ensureSubscribed @ withMqttConnected.js:50
> value @ withMqttConnected.js:15
> ks @ react-dom.production.min.js:251
> t.unstable_runWithPriority @ scheduler.production.min.js:18
> Yi @ react-dom.production.min.js:120
> Bs @ react-dom.production.min.js:244
> As @ react-dom.production.min.js:223
> (anonymous) @ react-dom.production.min.js:121
> t.unstable_runWithPriority @ scheduler.production.min.js:18
> Yi @ react-dom.production.min.js:120
> Ji @ react-dom.production.min.js:121
> Qi @ react-dom.production.min.js:120
> bs @ react-dom.production.min.js:214
> enqueueSetState @ react-dom.production.min.js:133
> v.setState @ react.production.min.js:13
> s.onStateChange @ connectAdvanced.js:207
> notify @ Subscription.js:23
> t.notifyNestedSubs @ Subscription.js:62
> s.onStateChange @ connectAdvanced.js:204
> b @ createStore.js:172
> (anonymous) @ index.js:68
> u @ runtime.js:45
> (anonymous) @ runtime.js:271
> forEach.e.<computed> @ runtime.js:97
> u @ runtime.js:45
> t @ runtime.js:135
> (anonymous) @ runtime.js:145
> paho-mqtt-min.js:37 WebSocket connection to 'ws://grafolean.unimax.local/mqtt' failed: 
> d._doConnect @ paho-mqtt-min.js:37
> d._disconnected @ paho-mqtt-min.js:58
> d._on_socket_error @ paho-mqtt-min.js:52
> (anonymous) @ paho-mqtt-min.js:17
> MQTTFetcherSingleton.js:135 Error connecting to MQTT broker via WebSockets
> onFailure @ MQTTFetcherSingleton.js:135
> d._disconnected @ paho-mqtt-min.js:58
> d._on_socket_error @ paho-mqtt-min.js:52
> (anonymous) @ paho-mqtt-min.js:17
> error (async)
> d._doConnect @ paho-mqtt-min.js:38
> d._disconnected @ paho-mqtt-min.js:58
> d._on_socket_error @ paho-mqtt-min.js:52
> (anonymous) @ paho-mqtt-min.js:17
> error (async)
> d._doConnect @ paho-mqtt-min.js:38
> d.connect @ paho-mqtt-min.js:31
> G.connect @ paho-mqtt-min.js:69
> (anonymous) @ MQTTFetcherSingleton.js:128
> ensureMqttConnected @ MQTTFetcherSingleton.js:115
> t.ensureSubscribed @ withMqttConnected.js:50
> value @ withMqttConnected.js:15
> ks @ react-dom.production.min.js:251
> t.unstable_runWithPriority @ scheduler.production.min.js:18
> Yi @ react-dom.production.min.js:120
> Bs @ react-dom.production.min.js:244
> As @ react-dom.production.min.js:223
> (anonymous) @ react-dom.production.min.js:121
> t.unstable_runWithPriority @ scheduler.production.min.js:18
> Yi @ react-dom.production.min.js:120
> Ji @ react-dom.production.min.js:121
> Qi @ react-dom.production.min.js:120
> bs @ react-dom.production.min.js:214
> enqueueSetState @ react-dom.production.min.js:133
> v.setState @ react.production.min.js:13
> s.onStateChange @ connectAdvanced.js:207
> notify @ Subscription.js:23
> t.notifyNestedSubs @ Subscription.js:62
> s.onStateChange @ connectAdvanced.js:204
> b @ createStore.js:172
> (anonymous) @ index.js:68
> u @ runtime.js:45
> (anonymous) @ runtime.js:271
> forEach.e.<computed> @ runtime.js:97
> u @ runtime.js:45
> t @ runtime.js:135
> (anonymous) @ runtime.js:145
> Promise.then (async)
> t @ runtime.js:144
> (anonymous) @ runtime.js:145
> Promise.then (async)
> t @ runtime.js:144
> (anonymous) @ runtime.js:170
> o @ runtime.js:169
> _invoke @ runtime.js:192
> forEach.e.<computed> @ runtime.js:97
> e.async @ runtime.js:216
> a.handleLoginSubmit @ index.js:34
> m @ react-dom.production.min.js:15
> A @ react-dom.production.min.js:15
> (anonymous) @ react-dom.production.min.js:16
> z @ react-dom.production.min.js:16
> T @ react-dom.production.min.js:17
> S @ react-dom.production.min.js:17
> L @ react-dom.production.min.js:17
> wn @ react-dom.production.min.js:81
> ue @ react-dom.production.min.js:285
> Tn @ react-dom.production.min.js:83
> qn @ react-dom.production.min.js:84
> Ln @ react-dom.production.min.js:84
> t.unstable_runWithPriority @ scheduler.production.min.js:18
> Yi @ react-dom.production.min.js:120
> ce @ react-dom.production.min.js:285
> Sn @ react-dom.production.min.js:82
> withMqttConnected.js:57 Could not connect to MQTT undefined
> (anonymous) @ withMqttConnected.js:57
> Promise.catch (async)
> t.ensureSubscribed @ withMqttConnected.js:56
> value @ withMqttConnected.js:15
> ks @ react-dom.production.min.js:251
> t.unstable_runWithPriority @ scheduler.production.min.js:18
> Yi @ react-dom.production.min.js:120
> Bs @ react-dom.production.min.js:244
> As @ react-dom.production.min.js:223
> (anonymous) @ react-dom.production.min.js:121
> t.unstable_runWithPriority @ scheduler.production.min.js:18
> Yi @ react-dom.production.min.js:120
> Ji @ react-dom.production.min.js:121
> Qi @ react-dom.production.min.js:120
> bs @ react-dom.production.min.js:214
> enqueueSetState @ react-dom.production.min.js:133
> v.setState @ react.production.min.js:13
> s.onStateChange @ connectAdvanced.js:207
> notify @ Subscription.js:23
> t.notifyNestedSubs @ Subscription.js:62
> s.onStateChange @ connectAdvanced.js:204
> b @ createStore.js:172
> (anonymous) @ index.js:68
> u @ runtime.js:45
> (anonymous) @ runtime.js:271
> forEach.e.<computed> @ runtime.js:97
> u @ runtime.js:45
> t @ runtime.js:135
> (anonymous) @ runtime.js:145
> Promise.then (async)
> t @ runtime.js:144
> (anonymous) @ runtime.js:145
> Promise.then (async)
> t @ runtime.js:144
> (anonymous) @ runtime.js:170
> o @ runtime.js:169
> _invoke @ runtime.js:192
> forEach.e.<computed> @ runtime.js:97
> e.async @ runtime.js:216
> a.handleLoginSubmit @ index.js:34
> m @ react-dom.production.min.js:15
> A @ react-dom.production.min.js:15
> (anonymous) @ react-dom.production.min.js:16
> z @ react-dom.production.min.js:16
> T @ react-dom.production.min.js:17
> S @ react-dom.production.min.js:17
> L @ react-dom.production.min.js:17
> wn @ react-dom.production.min.js:81
> ue @ react-dom.production.min.js:285
> Tn @ react-dom.production.min.js:83
> qn @ react-dom.production.min.js:84
> Ln @ react-dom.production.min.js:84
> t.unstable_runWithPriority @ scheduler.production.min.js:18
> Yi @ react-dom.production.min.js:120
> ce @ react-dom.production.min.js:285
> Sn @ react-dom.production.min.js:82
> withMqttConnected.js:57 Could not connect to MQTT undefined
> (anonymous) @ withMqttConnected.js:57
> Promise.catch (async)
> t.ensureSubscribed @ withMqttConnected.js:56
> value @ withMqttConnected.js:15
> ks @ react-dom.production.min.js:251
> t.unstable_runWithPriority @ scheduler.production.min.js:18
> Yi @ react-dom.production.min.js:120
> Bs @ react-dom.production.min.js:244
> As @ react-dom.production.min.js:223
> (anonymous) @ react-dom.production.min.js:121
> t.unstable_runWithPriority @ scheduler.production.min.js:18
> Yi @ react-dom.production.min.js:120
> Ji @ react-dom.production.min.js:121
> Qi @ react-dom.production.min.js:120
> bs @ react-dom.production.min.js:214
> enqueueSetState @ react-dom.production.min.js:133
> v.setState @ react.production.min.js:13
> s.onStateChange @ connectAdvanced.js:207
> notify @ Subscription.js:23
> t.notifyNestedSubs @ Subscription.js:62
> s.onStateChange @ connectAdvanced.js:204
> b @ createStore.js:172
> (anonymous) @ index.js:68
> u @ runtime.js:45
> (anonymous) @ runtime.js:271
> forEach.e.<computed> @ runtime.js:97
> u @ runtime.js:45
> t @ runtime.js:135
> (anonymous) @ runtime.js:145
> Promise.then (async)
> t @ runtime.js:144
> (anonymous) @ runtime.js:145
> Promise.then (async)
> t @ runtime.js:144
> (anonymous) @ runtime.js:170
> o @ runtime.js:169
> _invoke @ runtime.js:192
> forEach.e.<computed> @ runtime.js:97
> e.async @ runtime.js:216
> a.handleLoginSubmit @ index.js:34
> m @ react-dom.production.min.js:15
> A @ react-dom.production.min.js:15
> (anonymous) @ react-dom.production.min.js:16
> z @ react-dom.production.min.js:16
> T @ react-dom.production.min.js:17
> S @ react-dom.production.min.js:17
> L @ react-dom.production.min.js:17
> wn @ react-dom.production.min.js:81
> ue @ react-dom.production.min.js:285
> Tn @ react-dom.production.min.js:83
> qn @ react-dom.production.min.js:84
> Ln @ react-dom.production.min.js:84
> t.unstable_runWithPriority @ scheduler.production.min.js:18
> Yi @ react-dom.production.min.js:120
> ce @ react-dom.production.min.js:285
> Sn @ react-dom.production.min.js:82

**Comment by smccloud** [comment]
Only a FQDN causes an issue, an IP address in EXTERNAL_HOSTNAME works fine.

**Comment by grafolean** [comment]
Closing this as stale, feel free to reopen if it still happens or if you have some additional info (there should be no difference between using an IP and FQDN in this case).

**Comment by bert2002** [comment]
I have the same problem and getting the following error in the console
```
Error connecting to MQTT broker via WebSockets
```
The `EXTERNAL_HOSTNAME` is correct set to an IP address, same as which I access the UI and could setup the admin user.

Anything else that I can check?

Thanks,
bert
