### ISSUE TITLE
Documentation doesn't seem to mention default NetFlow port

### ISSUE THREAD

**Issue by kevbo-oh** [grafolean/grafolean#48]
I'm setting up Grafolean for the first time to receive data from OpenWRT (using softflowd). Softflowd needs to know the port to connect to on the NetFlow collector, and I couldn't find any reference in the instructions as to what port to send it to.

I finally found something by searching through closed Issues, and discovered that it seems to be port 2055. I then searched the repo for 2055 and only found reference to it in Docker compose files...so I don't think I'm crazy. I don't think that port is mentioned in the normal documentation.

Maybe it should be? Or did I miss something?

Thanks for making this software available!

**Comment by grafolean** [comment]
Hi, thanks for providing the feedback!

I have updated the documentation (https://github.com/grafolean/grafolean/blob/master/doc/HOWTO-NetFlow.md#2-sending-netflow-data) with the requested information, please let me know if there is anything else missing.

Closing this issue as solved, but please reopen if you have any other suggestions on how to improve the installation documentation.
