### ISSUE TITLE
netflow-writer errors

### ISSUE THREAD

**Issue by psybernoid** [grafolean/grafolean#5]
Running docker version 19.03.13 build 4484c46d9d and docker-compose version 1.25.5, build 8a1c60f6 on Ubuntu 20.04, no netflow data is displaying on dashboard. Grafolean does detect initial netflow source and allows me to assign a sensor.

Netflow source is routerOS 6.47.4 with netflow version 9 being sent.

docker logs grafolean-netflow-writer output is a continuous result of

```
2020-10-11 16:18:22.463 | ERR | Error writing line, skipping...
Traceback (most recent call last):
  File "./netflowwriter.py", line 117, in process_named_pipe
  File "./netflowwriter.py", line 255, in write_buffer
  File "./netflowwriter.py", line 211, in _get_data
KeyError: 'DIRECTION'
```

**Comment by grafolean** [comment]
Hi @psybernoid, thanks for reporting this!

It looks like direction is not specified in these flows for some reason. I don't have a MikroTik at hand for testing, but I have made the field optional (it now defaults to ingress, as with NetFlow v5) as there is no downside to this change (`grafolean-netflow-bot` version v0.2.9). 

Would you be willing to test it?

First you need to upgrade the `grafolean-netflow-bot` docker image:
```
$ docker pull grafolean/grafolean-netflow-bot
...
Digest: sha256:37ef8a2cd44fc77512948c7d1d91cea9537bac381ea2a3b33cf4bd0c0eac48d7
...
```

And then restart Grafolean:
```
$ docker-compose down
$ docker-compose up -d
```

Let me know if it works, otherwise I'll try to get some MikroTik router somewhere for testing.

**Comment by psybernoid** [comment]
So, the error has now changed to:

```
2020-10-11 18:26:00.476 | ERR | Error writing line, skipping...
Traceback (most recent call last):
  File "./netflowwriter.py", line 136, in process_named_pipe
  File "./netflowwriter.py", line 255, in write_buffer
  File "./netflowwriter.py", line 221, in _get_data
KeyError: 'IPV4_DST_ADDR'
```

It's possible, for testing to use either the x86 or CHR versions of RouterOS, which can be installed in a VM - I believe it's fully functional without a license, but with a limit on each interface set at 1Gb/s https://mikrotik.com/download

Happy to do some further testing either way though!

**Comment by grafolean** [comment]
Thanks for the links, I'll take a look at them. If you're willing to test further though, it is of course easier for me... :)

Do you happen to be using IPv6? Currently only IPv4 is supported, but there is no special reason for it - just nobody needed it yet. I can add it quickly if this is the issue?

**Comment by psybernoid** [comment]
I'm not using IPv6, no. But the package was enabled. I've disabled the package, but still getting the same error.

**Comment by grafolean** [comment]
Ok, thanks.

The good news is, I managed to get MikroTik VM running and configured it so that it was sending NetFlow v9 to some new installation of Grafolean. The bad news is, I can't replicate the problem - while it did take ~5 minutes before it started gathering data (log message: `Failed to decode a v9 ExportPacket, template not recognized (if this happens at the start, it's ok)`), once it started receiving data (log message: `Last record sequence number is not known, starting with 34`) it worked and didn't throw any new warnings or error messages... :-/

I am reluctant to just ignore this error because we don't know the reason for it and its impact... However, I have now made a new version of `grafolean-netflow-bot` (v0.2.10) which catches the error and:
- logs the contents of the flow record (so we can investigate), and
- continues work on any other records in the same packet.

Could you try it out and let me know how it goes?

**Comment by psybernoid** [comment]
Looks like that version isn't publicly available

```
Using default tag: latest
Error response from daemon: pull access denied for grafolean-netflow-bot, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

Whilst we're at it, how have to configured the traffic-flow on your VM? Have to specified a source IP, or just a target?

**Comment by grafolean** [comment]
This happens sometime with `docker pull`, though it works for me:
```
$ docker pull grafolean/grafolean-netflow-bot
Using default tag: latest
latest: Pulling from grafolean/grafolean-netflow-bot
...
Digest: sha256:7822f9e68bc98c50e453c5cb9af0aa32efb17d7205cf6c74af7ec152f030a53a
Status: Downloaded newer image for grafolean/grafolean-netflow-bot:latest
```

Still, I re-published the image just to be on the safe side.

> Whilst we're at it, how have you configured the traffic-flow on your VM? Have you specified a source IP, or just a target?

Just the target:
```
[admin@MikroTik] ip traffic-flow target> add dst-address=192.168.0.2 port=2055 version=9
```
(taken from [MikroTik NetFlow docs](https://wiki.mikrotik.com/wiki/Manual:IP/Traffic_Flow))

**Comment by psybernoid** [comment]
So, it does appear that having the IPv6 package enabled on a Mikrotik router (which it is by default, at least on my RB4011) is causing the issue.

I've pointed another Mikrotik device at it - in this case, an hAPac and I'm getting data.

So here's the output with IPv6 enabled:

```
| ERR | [10.0.0.254] Error decoding v9 flow, some data was missing. Contents: {'IP_PROTOCOL_VERSION': 6, 'IPV6_SRC_ADDR': 'fe80::1434:4ff:fe5a:bb49', 'IPV6_SRC_MASK': 0, 'INPUT_SNMP': 14, 'IPV6_DST_ADDR': 'ff02::2', 'IPV6_DST_MASK': 0, 'OUTPUT_SNMP': 0, 'IPV6_NEXT_HOP': 'ff02::2', 'PROTOCOL': 58, 'TCP_FLAGS': 0, 'SRC_TOS': 0, 'L4_SRC_PORT': 0, 'L4_DST_PORT': 0, 'IPV6_FLOW_LABEL': 0, 'IPV6_OPTION_HEADERS': 0, 'LAST_SWITCHED': 171512910, 'FIRST_SWITCHED': 171512910, 'IN_BYTES': 56, 'IN_PKTS': 1, 'IN_DST_MAC': 56294136348674, 'IN_SRC_MAC': 127874737942847, 'OUT_DST_MAC': 70975890555444, 'OUT_SRC_MAC': 0}
Traceback (most recent call last):
  File "./netflowwriter.py", line 222, in _get_data
KeyError: 'IPV4_DST_ADDR'
2020-10-12 07:33:50.478 | INF | Opened named pipe /shared-grafolean/netflow.pipe
```

With Traffic-Flow disabled on the RB4011 and only enabled on the hAPac, this is all that's logged:

`2020-10-12 09:08:28.914 | INF | Opened named pipe /shared-grafolean/netflow.pipe`

I'll completely diable the IPv6 package on the RB4011 later, when I'm not using the connection.
However, if it's possible, would allowing IPv6 in the netflow-bot be an option? As if another Mikrotik user decides to use this, they may encounter the same issue.

**Comment by grafolean** [comment]
Nice, thank you very much for your help in debugging this!

> However, if it's possible, would allowing IPv6 in the netflow-bot be an option? As if another Mikrotik user decides to use this, they may encounter the same issue.

Absolutely. Even this version of netflow bot (v0.2.10) would "work" in the sense that it would ignore (and log) all IPv6 flows while still collect all IPv4 ones. However this is not ideal as the logs will be very verbose and IPv6 data is not monitored.

I checked what changes would need to be made for IPv6 and it looks like this would be a breaking change (in a sense that daily aggregates of netflow data would be reset) and not as simple as I thought at first. So as a first step, I will just improve logging to warn about IPv6 explicitly and to make sure there are less errors logged (now there is one log entry for each flow record which is too much). 

Just to make sure I understand the priority of this correctly, you don't actually need to monitor IPv6 traffic at the moment? That is, as long as it shows correct data for IPv4, this is enough for now?

**Comment by psybernoid** [comment]
Yes. I have no use for IPv6 at present.

Thanks however for developing a very useful tool.

**Comment by grafolean** [comment]
No problem, glad you find it useful! 

Version [v0.2.11](https://github.com/grafolean/grafolean-netflow-bot/releases/tag/v0.2.11) of `grafolean-netflow-bot` now gracefully handles IPv6 traffic (logs that it is not yet supported).

As the original problem seems to be solved, I will now close this issue, but will still see what I can do about IPv6 support.

If you encounter any other problem or have some suggestions on how to make this tool better, please do open another issue - I'd be happy to help. And thanks again for reporting this bug!

**Comment by grafolean** [comment]
@psybernoid Just a thumbs up - NetFlow bot now supports IPv6 (Grafolean v0.4.3 and Grafolean NetFlow bot v0.2.11).
